language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.6'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: mrahnis
  password:
    secure: aYI/XrfuzOHC+Di44PmNoGBPrOjovSXFvr/5PwhzBJBI2RfgT2XidL4mWhZ6qK8ppEqstlU1gE+bB8eVn6CArR1KrLF6zGCtPz7Y2YRjZRfx0/AR6cmpf7DKPICsyADp0Z4w8SzS+4axHdosIqaqCK4TrZI65DinbvDFwq+f0G2TCB+1CnmZFAgKUlTbn9zWTKH23JlcxsXe2M4KP46lWcQkDm8yqI4iF9STvNvPm5xrK0vaBBJfq8f638z/Ao7rSH0+ZJbTYZ/Tdqz8bXekIi6eqhS89YkCIMxMkRA/yXdAylbhjcvzNP1GoT2WYpEHeCNIqW4YsegdvcTc1r9S2PFQUQ2UpO2rx6B+7+dPuyNieCG30XySK5q9XLQkkYXqGoYT33I8NPoi4tqQ0Nrn9jWNOdXZKfstHokKiEus5bV47JOoUYFNAIGAIot2LWZlzp/WmJwROa6x9M8V1vnawRT4Q27zVyzCDcU0RpbUcBgVuX53z3v0U+xKIrXkA4sfwqNxdYURX+Vpsu0drx3wNKykytjRHoanetbzi2RMBIXvPjcQ3hkE1yu5PeuCK71W5rSkQ/RTOqNT9rWNaCfbUraowEEpekOY+onSo2ygYrJH4GSApb4QR3BFE1KCAA42sdd43UMAnDrYeooiIA/h+VSidzLRpJBGLt5M+TkBebc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/drapery
  skip_cleanup: true
