[project]
name = "drapery"
version = "0.0.1"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
rasterio = ">=1.3.9,<1.4"
click = ">=8.1.7,<8.2"
pip = ">=23.3.2,<23.4"
setuptools = ">=69.0.3,<69.1"
fiona = ">=1.9.5,<1.10"
python = ">=3.12.1,<3.13"
shapely = ">=2.0.2,<2.1"
