name: rio
dependencies:
    - anaconda-client
    - conda-build
    - conda-verify
    - pytest
    - python
    - cython
    - numpy
    - scipy
    - matplotlib
    - rasterio
    - click
    - crick 
