{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: drapery
  version: {{ version }}

source:
  git_url: ../
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - drape = drapery.cli.drape:cli
    
requirements:
  build:
    - python
    - setuptools
  run:
    {% for dependency in pyproject['dependencies'] %}
    - {{ dependency.lower() }}
    {% endfor %}

test:
  imports:
    - drapery
  commands:
    - drape --help

about:
  home: https://github.com/mrahnis/drapery
  description: Python library and CLI tool to convert 2D geometries to 3D given an elevation source
  license: BSD
  license_file: LICENSE.txt

# https://github.com/conda/conda-build/issues/4807
# whatever_you_do_don't_load_setup_py_dataxxx!!!
