{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: drapery
  version: {{ version }}

source:
  git_url: ../
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: python -m pip install --single-version-externally-managed --record=record.txt
  entry_points:
    - drape = drapery.cli.drape:cli
    
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - shapely
    - rasterio
    - fiona

test:
  imports:
    - drapery
  commands:
    - drape --help

about:
  home: https://github.com/mrahnis/drapery
  description: Python library and CLI tool to convert 2D geometries to 3D given an elevation source
  license: BSD
  license_file: LICENSE.txt